from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
BUILD_ROOT = PROJECT_ROOT / "build"
OUTPUT_DIR = BUILD_ROOT / "web_vercel"

# Keep in sync with lib/config/app_config.dart defaults.
_DEFAULT_SUPABASE_URL = "https://szerwpvldtnamhfpqmih.supabase.co"
_DEFAULT_SUPABASE_ANON_KEY = (
    "sb_publishable_gmJyumfHSnoOTqpMkVS-qw_A6axiU62"
)


def optional_env(name: str) -> str:
    return os.environ.get(name, "").strip()


def resolve_flutter_exe() -> str:
    configured = optional_env("FLUTTER_EXE")
    if configured:
        configured_path = Path(configured)
        if configured_path.is_absolute():
            return str(configured_path)
        return str((PROJECT_ROOT / configured_path).resolve())

    default_exe_name = "flutter.bat" if os.name == "nt" else "flutter"
    local_flutter = PROJECT_ROOT / "flutter" / "bin" / default_exe_name
    if local_flutter.exists():
        return str(local_flutter)

    for candidate in ("flutter.bat", "flutter") if os.name == "nt" else ("flutter",):
        found = shutil.which(candidate)
        if found:
            return found

    raise FileNotFoundError(
        "Flutter executable not found. Set FLUTTER_EXE to your flutter "
        f"(or {default_exe_name}) path, or clone Flutter into ./flutter "
        "(see vercel.json installCommand)."
    )


def copy_project() -> Path:
    temp_project = Path(tempfile.mkdtemp(prefix="core_review_web_"))
    shutil.copytree(
        PROJECT_ROOT,
        temp_project,
        ignore=shutil.ignore_patterns(
            "build",
            ".dart_tool",
            ".idea",
            "windows",
            "android",
            "test",
            "assets/book_images",
        ),
        dirs_exist_ok=True,
    )
    return temp_project


def copy_book_images(output_dir: Path) -> None:
    """Copy book_images to output so they are served at /book_images/."""
    source = PROJECT_ROOT / "assets" / "book_images"
    if not source.exists():
        return
    dest = output_dir / "book_images"
    if dest.exists():
        shutil.rmtree(dest, ignore_errors=True)
    shutil.copytree(source, dest, dirs_exist_ok=True)


def trim_pubspec_assets(temp_project: Path) -> None:
    pubspec_path = temp_project / "pubspec.yaml"
    pubspec = pubspec_path.read_text(encoding="utf-8")
    pubspec = pubspec.replace("    - assets/book_images/\n", "")
    pubspec_path.write_text(pubspec, encoding="utf-8", newline="\n")


def write_question_chunks(project_root: Path) -> None:
    data_dir = project_root / "assets" / "data"
    questions_path = data_dir / "questions.json"
    if not questions_path.exists():
        return

    questions = json.loads(questions_path.read_text(encoding="utf-8"))
    output_dir = data_dir / "questions"
    if output_dir.exists():
        shutil.rmtree(output_dir, ignore_errors=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    questions_by_book: dict[str, list[dict[str, object]]] = {}
    for question in questions:
        book_id = str(question["bookId"])
        questions_by_book.setdefault(book_id, []).append(question)

    for book_id, entries in questions_by_book.items():
        (output_dir / f"{book_id}.json").write_text(
            json.dumps(entries, separators=(",", ":")),
            encoding="utf-8",
        )


def run(command: list[str], *, cwd: Path) -> None:
    subprocess.run(command, cwd=str(cwd), check=True)


def write_api_supabase_build_config() -> None:
    """Emit api/_build_supabase_config.js so serverless routes use the same Supabase
    URL + anon key as the Flutter web bundle (see api/study-progress.js)."""
    url = optional_env("SUPABASE_URL") or optional_env("NEXT_PUBLIC_SUPABASE_URL")
    if not url:
        url = _DEFAULT_SUPABASE_URL
    anon = optional_env("SUPABASE_ANON_KEY") or optional_env("NEXT_PUBLIC_SUPABASE_ANON_KEY")
    if not anon:
        anon = _DEFAULT_SUPABASE_ANON_KEY
    out = PROJECT_ROOT / "api" / "_build_supabase_config.js"
    out.write_text(
        "// Generated by tool/build_web_for_vercel.py — matches Flutter dart-define Supabase.\n"
        f"module.exports = {{ url: {json.dumps(url)}, anonKey: {json.dumps(anon)} }};\n",
        encoding="utf-8",
        newline="\n",
    )


def main() -> None:
    write_api_supabase_build_config()
    supabase_url = optional_env("SUPABASE_URL")
    supabase_anon_key = optional_env("SUPABASE_ANON_KEY")
    auth_redirect_url = optional_env("AUTH_REDIRECT_URL")
    # CONTENT_BASE_URL is no longer needed — the app resolves image URLs from
    # window.location.origin at runtime, so they never go stale across deploys.
    # Keep reading it here in case a future env var override is useful.
    content_base_url = optional_env("CONTENT_BASE_URL")
    flutter_exe = resolve_flutter_exe()

    temp_project = copy_project()
    trim_pubspec_assets(temp_project)
    write_question_chunks(temp_project)

    run([flutter_exe, "pub", "get"], cwd=temp_project)
    run([flutter_exe, "create", ".", "--platforms=web"], cwd=temp_project)
    build_command = [
        flutter_exe,
        "build",
        "web",
        "--release",
        "--pwa-strategy=none",
    ]
    if content_base_url:
        build_command.append(f"--dart-define=CONTENT_BASE_URL={content_base_url}")
    if supabase_url:
        build_command.append(f"--dart-define=SUPABASE_URL={supabase_url}")
    if supabase_anon_key:
        build_command.append(f"--dart-define=SUPABASE_ANON_KEY={supabase_anon_key}")
    if auth_redirect_url:
        build_command.append(f"--dart-define=AUTH_REDIRECT_URL={auth_redirect_url}")

    run(build_command, cwd=temp_project)

    built_web_dir = temp_project / "build" / "web"
    if OUTPUT_DIR.exists():
        shutil.rmtree(OUTPUT_DIR, ignore_errors=True)
    shutil.copytree(built_web_dir, OUTPUT_DIR, dirs_exist_ok=True)
    shutil.copy2(PROJECT_ROOT / "vercel.json", OUTPUT_DIR / "vercel.json")
    # Do not copy repo `api/` into the static output. Vercel would otherwise
    # serve those `.js` files as static assets and the real `/api/*` serverless
    # routes (e.g. study-progress) would not run.
    copy_book_images(OUTPUT_DIR)
    shutil.rmtree(temp_project, ignore_errors=True)

    print(f"Web build ready at {OUTPUT_DIR}")
    print(
        "Set CONTENT_BASE_URL to your deployment URL (e.g. https://your-project.vercel.app)"
        " so images load from /book_images/"
    )


if __name__ == "__main__":
    main()
